Create contributing.md
shtormtech/.github pull request #1
Opened 2020-08-10 17:07 UTC by Iloer

2020-08-10 18:51 UTC, nprovotorov commented on contributing.md
> +Нет необходимости включать в наименование ничего не значащие или понятные только вам аббревиатуры, постфиксы, указания на нежелаемое поведение.
как насчет прописать правила именований для feature и fix веток отдельно и в явном виде?

2020-08-10 18:51 UTC, nprovotorov commented on contributing.md
> +1. Commit - Внесите необходимые изменения в код проекта, оставляя внятные комментарии описывающие суть вносимых изменений, указанием на ISSUE которое вы решаете и с соблюдением принятого в основном р
хорошо бы дать ссылку на style guide

2020-08-10 18:51 UTC, nprovotorov commented on contributing.md
> +### Завести дифект
какие-то минимальные требования к информации о дефекте? Дата, время, ОС, логи, и т.д.?

2020-08-10 18:51 UTC, nprovotorov commented on contributing.md
> +### Предложить изменение
какие-то требования к описанию предложения? типа "Зачем?", для кого? и т.д.

2020-08-10 18:51 UTC, nprovotorov commented on contributing.md
> +### Завести дифект
хорошо бы дать описание хотя бы первоначальным label-ам

2020-08-16 18:34 UTC, Iloer commented on contributing.md
> +Нет необходимости включать в наименование ничего не значащие или понятные только вам аббревиатуры, постфиксы, указания на нежелаемое поведение.
Давайте пока не будем делить ветки по назначению

2020-08-16 18:44 UTC, Iloer commented on contributing.md
> +1. Commit - Внесите необходимые изменения в код проекта, оставляя внятные комментарии описывающие суть вносимых изменений, указанием на ISSUE которое вы решаете и с соблюдением принятого в основном р
done!

2020-08-16 19:12 UTC, Iloer commented on contributing.md
> +### Завести дифект
done!

2020-08-16 19:19 UTC, Iloer commented on contributing.md
> +### Предложить изменение
done!

2020-08-16 19:33 UTC, Iloer commented on contributing.md
> +### Завести дифект
done!

2020-08-17 06:23 UTC, nprovotorov commented on contributing.md
> +Вы уже проверили существующий список предложений и убедились, что интересующий вас функцинал ренее никем не предложен. Тогда пжалуйста опишите максимально подробно ваше предлжение. Сформулируйте пове
"пжалуйста"

2020-08-17 06:30 UTC, Iloer commented on contributing.md
> +Вы уже проверили существующий список предложений и убедились, что интересующий вас функцинал ренее никем не предложен. Тогда пжалуйста опишите максимально подробно ваше предлжение. Сформулируйте пове
done

2020-08-17 06:49 UTC, nprovotorov submitted a review, later dismissed

2020-08-17 06:50 UTC, nprovotorov submitted a review, later dismissed

2020-08-17 19:21 UTC, maximza requested changes
@Iloer , моя все, сорян, но я не смог удержаться и просто апрувнуть :(

2020-08-17 19:21 UTC, maximza commented on contributing.md
> +Перед тем как предложить описание нового дефекта, новой фичи прошу посмотреть в раздел issues на предмет того, что данный дефект/фича, либо уже не решены, либо не находятся в стадии обсуждения или ра
Я бы общие доки писал обезличенно или от лица команды/компании, т.е. не прошу, а просто "перед тем как предложить дефект, посмотрите раздел issues, возможно вы там него уже найдете"

2020-08-17 19:21 UTC, maximza commented on contributing.md
> +## Как я могу внести свой вклад
```suggestion
# Как я могу внести свой вклад
```

2020-08-17 19:21 UTC, maximza commented on contributing.md
> +Перед тем как предложить описание нового дефекта, новой фичи прошу посмотреть в раздел issues на предмет того, что данный дефект/фича, либо уже не решены, либо не находятся в стадии обсуждения или ра
```suggestion
Привет! Для начала, спасибо, что хотите помочь с развитием проекта и интересуетесь, как это сделать правильно 👍 

Ниже приводятся наши рекомендации, следуя которым будет просто и удобно содержать репозиторий в "чистоте" и порядке. Так, что, пожалуйста, прочтите, если вы хотите:
- [завести баг](#Завести-дефект)
- [завести пожелание](#Предложить-изменение)
- [внести изменение/дополнение](#Внести-изменение/дополнение)

## Кодекс поведения участника
Этот проект и любой его участник обязуется соблюдать кодекс поведения участника. В качестве кодекса мы используем [Contributor Covenant v 2.0](https://www.contributor-covenant.org/ru/version/2/0/code_of_conduct/)

```

@nprovotorov , contributor covenant рекомендую еще и для того, чтобы на него посмотреть при создании кодекса поведения для ШТОРМ в целом, в рамках развития истории с ценностями.

2020-08-17 19:21 UTC, maximza commented on contributing.md
> +### Внести изменение/дополнение
```suggestion
## Внести изменение/дополнение
```

2020-08-17 19:21 UTC, maximza commented on contributing.md
> +#1234. Выгрузка отчета в формате CSV.
```suggestion
> #1234. Выгрузка отчета в формате CSV.

```

2020-08-17 19:21 UTC, maximza commented on contributing.md
> +### Предложить изменение
Я бы подвинул вверх по иерархии до внесения изменений

2020-08-17 19:21 UTC, maximza commented on contributing.md
> +### Предложить изменение
```suggestion
## Предложить изменение
```

2020-08-17 19:21 UTC, maximza commented on contributing.md
> +### Завести дефект
```suggestion
## Завести дефект 
```

2020-08-17 19:21 UTC, maximza commented on contributing.md
> +Вы уже проверили существующий список предложений и убедились, что интересующий Вас функцинал ренее никем не предложен. Тогда, пожалуйста, опишите максимально подробно Ваше предложение. Сформулируйте
```suggestion
Вы уже проверили существующий список предложений и убедились, что интересующий Вас функцинал ренее никем не предложен. Тогда, пожалуйста, опишите максимально подробно Ваше предложение. Сформулируйте поведение решения сейчас и как оно изменится после реализации вашего предложения. Какую проблему Вы пытаетесь решить? Кому будет полезна реализация вашего предложения.

```

2020-08-17 19:21 UTC, maximza commented on contributing.md
> +### Style guides
Я бы это все (style-guide, labels) перенес в блок про PR.

2020-08-17 19:21 UTC, maximza commented on contributing.md
> +#### Pull Request
Тут внутри предлагаю сделать еще парочку вещей:
- чек-лист подготовки к PR-у (проверили по стайл-гайду, желательно обновились с основного репо, протестировали изменения локально и т.п.)
- общее описание того, что будет с PRом - типа сделал, в течении недели мэйнтейнер посмотрит на него даст комменты или заапрувит и вольет

2020-08-17 19:21 UTC, maximza commented on contributing.md
> +Перед тем как предложить описание нового дефекта, новой фичи прошу посмотреть в раздел issues на предмет того, что данный дефект/фича, либо уже не решены, либо не находятся в стадии обсуждения или ра
И тут еще одно - я бы это перенес в раздел посвященный созданию дефектов

2020-08-18 05:22 UTC, Iloer commented on contributing.md
> +### Style guides
В какой именно блок про ПР? 
Если там где порядок действий описан, то нет, он не про то.
Если про именование, то там тоже только об именовании, а не способах кодирования.
Давай оставим отдельными разделами.

2020-08-18 05:29 UTC, Iloer commented on contributing.md
> +Перед тем как предложить описание нового дефекта, новой фичи прошу посмотреть в раздел issues на предмет того, что данный дефект/фича, либо уже не решены, либо не находятся в стадии обсуждения или ра
Текст больше не актуален.

2020-08-18 05:30 UTC, Iloer commented on contributing.md
> +Перед тем как предложить описание нового дефекта, новой фичи прошу посмотреть в раздел issues на предмет того, что данный дефект/фича, либо уже не решены, либо не находятся в стадии обсуждения или ра
Текст больше не актуален.

2020-08-18 05:35 UTC, Iloer commented on contributing.md
> +#### Pull Request
* Давай тут пожалуйста без чеклистов обойдемся, я надеюсь, что те кто читают этот документ, достаточно сознательны, чтобы им не проговаривать очевидное.
* описывая, то, что произойдет с ПР, мы берем на себя некие гарантии, того как это будет происходить, а не имея опыта просмотра и принятия реквестов (кто будет смотреть, когда будет смотреть, как проверять, сколько на это ужно времени), сложно что-то гарантировать.

2020-08-18 06:23 UTC, maximza commented on contributing.md
> +#### Pull Request
ок, давай проверим твои надежды, плюс потренируемся на кошках с первыми PRами, чтобы понять что тут стоит описать

2020-08-18 06:24 UTC, maximza commented on contributing.md
> +Перед тем как предложить описание нового дефекта, новой фичи прошу посмотреть в раздел issues на предмет того, что данный дефект/фича, либо уже не решены, либо не находятся в стадии обсуждения или ра
Хороший текст то, чего не актуален?

2020-08-18 06:28 UTC, maximza commented on contributing.md
> +Перед тем как предложить описание нового дефекта, новой фичи прошу посмотреть в раздел issues на предмет того, что данный дефект/фича, либо уже не решены, либо не находятся в стадии обсуждения или ра
а, понял, вопрос снимается

2020-08-18 06:29 UTC, maximza commented on contributing.md
> +### Style guides
Ок, просто в структуру не очень ложиться... в какой момент времени мы ожидаем, что человек сюда должен посмотреть? Когда изменения начнет делать? Я бы в общем оттуда, где надо попользоваться style guide-ом, сделалы бы реф сюда, чтобы в целом contribution смотрелся целостным с точки зрения повествования. Ну или может его переместить внутрь "Внести изменение/дополнение"?

2020-08-18 07:30 UTC, Iloer commented on contributing.md
> +### Style guides
Так есть же ссылка на Style Guide из шага Commit в разделе "Внести изменение/дополнение"

2020-08-18 08:09 UTC, maximza commented on contributing.md
> +### Style guides
я слепой, сорян :(

2020-08-18 08:10 UTC, maximza approved these changes
Погнали дальше, все зарезолвил :)

2020-08-18 08:43 UTC, nprovotorov approved these changes

2020-08-18 08:43 UTC, merged